# Generated by Django 2.2.1 on 2019-05-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASC_COLLEGE_ID', models.CharField(max_length=25)),
                ('ORG_FULL_NAME', models.CharField(max_length=255)),
                ('CB_REGION_CD', models.CharField(default='NaN', max_length=25)),
                ('VISIT_STATE_CD', models.CharField(default='NaN', max_length=25)),
                ('MAIL_CITY', models.CharField(max_length=25, null=True)),
                ('GRAD_6_YR_RATE_PCT', models.CharField(blank=True, max_length=5, null=True)),
                ('ENROLL_UG_TOTAL_DEG', models.IntegerField(blank=True, null=True)),
                ('UNDERGRAD_GRADE_CD', models.CharField(blank=True, max_length=5, null=True)),
                ('FRESH_SAT_I_V_25_PCTL', models.IntegerField(blank=True, null=True)),
                ('FRESH_SAT_I_V_75_PCTL', models.IntegerField(blank=True, null=True)),
                ('FRESH_SAT_I_M_25_PCTL', models.IntegerField(blank=True, null=True)),
                ('FRESH_SAT_I_M_75_PCTL', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
